"use client";

import { useState } from "react";
import { EVALUATION_GRADES, type InterviewRecord } from "@/app/data/interviews";
import { validateInterviewResumeFile } from "@/app/data/interviews-adapter";
import { type CaseProfile } from "@/app/data/staffing-types";

const RATINGS = ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F"];
const OUTCOMES = ["Strong Hire", "Hire", "Maybe", "Hold", "Decline"] as const;
const CERTIFICATIONS = ["Active RBT", "CPR / First Aid", "Safety Care", "PCM", "Crisis Prevention / CPI", "Other"];
const SKILLS = ["Bilingual", "Sign Language", "Driver's License", "Reliable Transportation", "Willing to Travel", "Weekend Availability", "Comfortable In-Home", "Comfortable with Severe Behaviors", "Other"];
const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const EVALUATIONS = [["Communication", "communicationGrade"], ["Professionalism", "professionalismGrade"], ["ABA Experience", "abaExperienceGrade"], ["Schedule Flexibility", "scheduleFlexibilityGrade"], ["Overall Recommendation", "overallRecommendationGrade"]] as const;
const ONBOARDING = [["Background Check Submitted", "backgroundCheckSubmitted"], ["Background Cleared", "backgroundCleared"], ["Drug Screen", "drugScreen"], ["CPR Verified", "cprVerified"], ["RBT License Verified", "rbtLicenseVerified"]] as const;

type Draft = Omit<InterviewRecord, "id"> & { id?: string };
type Errors = Partial<Record<"candidateName" | "phone" | "email" | "city" | "state" | "scheduledAt", string>>;

function toLocalInput(value: string) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function controlClass(selected: boolean) { return `min-h-11 rounded-lg border-2 px-3 py-2 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 ${selected ? "border-blue-700 bg-blue-600 text-white shadow-sm shadow-blue-300 active:bg-blue-800" : "border-slate-300 bg-white text-slate-800 hover:border-blue-500 hover:bg-blue-50 active:bg-slate-100"}`; }
function ToggleSet({ options, values, onChange }: { options: string[]; values: string[]; onChange: (values: string[]) => void }) { return <div className="mt-2 flex flex-wrap gap-2">{options.map((option) => { const selected = values.includes(option); return <button key={option} type="button" aria-pressed={selected} onClick={() => onChange(selected ? values.filter((value) => value !== option) : [...values, option])} className={controlClass(selected)}>{option}</button>; })}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t border-slate-200 pt-5 first:border-t-0 first:pt-0"><h3 className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-700">{title}</h3><div className="mt-3">{children}</div></section>; }

export function InterviewFormModal({ initial, cases, saving, onClose, onSave, onRemoveResume, onViewResume }: { initial: Draft; cases: CaseProfile[]; saving: boolean; onClose: () => void; onSave: (draft: Draft, file: File | null) => void; onRemoveResume: (draft: Draft) => void; onViewResume: (draft: Draft) => void }) {
  const [form, setForm] = useState<Draft>(initial); const [file, setFile] = useState<File | null>(null); const [errors, setErrors] = useState<Errors>({}); const [resumeError, setResumeError] = useState("");
  const update = (patch: Partial<InterviewRecord>) => setForm((current) => ({ ...current, ...patch }));
  const validate = () => { const next: Errors = {}; if (!form.candidateName.trim()) next.candidateName = "Candidate name is required."; if (!form.phone.trim()) next.phone = "Phone is required."; if (!form.email.trim()) next.email = "Email is required."; if (!form.city.trim()) next.city = "City is required."; if (!form.state) next.state = "State is required."; if (!form.scheduledAt) next.scheduledAt = "Interview date and time are required."; setErrors(next); return Object.keys(next).length === 0; };
  const fieldClass = (error?: string) => `mt-1 w-full rounded-lg border bg-slate-50 px-3 py-2 text-sm ${error ? "border-rose-400" : "border-slate-200"}`;
  const required = (label: string) => <>{label} <span className="text-rose-600">*</span></>;
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/45 p-4"><div className="mx-auto my-4 w-full max-w-5xl rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4"><div><h2 className="text-lg font-semibold text-slate-900">{form.id ? "Edit Interview" : "Add Interview"}</h2><p className="mt-1 text-sm text-slate-500">Candidate details save directly to Supabase.</p></div><button type="button" onClick={onClose} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Close</button></div><div className="space-y-6 p-5">
    <Section title="Contact Information"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm text-slate-600">{required("Candidate Name")}<input value={form.candidateName} onChange={(event) => update({ candidateName: event.target.value })} className={fieldClass(errors.candidateName)} />{errors.candidateName ? <span className="mt-1 block text-xs text-rose-600">{errors.candidateName}</span> : null}</label><label className="text-sm text-slate-600">{required("Phone")}<input type="tel" value={form.phone} onChange={(event) => update({ phone: event.target.value })} className={fieldClass(errors.phone)} />{errors.phone ? <span className="mt-1 block text-xs text-rose-600">{errors.phone}</span> : null}</label><label className="text-sm text-slate-600">{required("Email")}<input type="email" value={form.email} onChange={(event) => update({ email: event.target.value })} className={fieldClass(errors.email)} />{errors.email ? <span className="mt-1 block text-xs text-rose-600">{errors.email}</span> : null}</label><label className="text-sm text-slate-600">{required("City")}<input value={form.city} onChange={(event) => update({ city: event.target.value })} className={fieldClass(errors.city)} />{errors.city ? <span className="mt-1 block text-xs text-rose-600">{errors.city}</span> : null}</label><label className="text-sm text-slate-600">{required("State")}<select value={form.state} onChange={(event) => update({ state: event.target.value })} className={fieldClass(errors.state)}><option value="">Select</option><option value="NM">New Mexico</option><option value="IA">Iowa</option></select>{errors.state ? <span className="mt-1 block text-xs text-rose-600">{errors.state}</span> : null}</label><label className="text-sm text-slate-600">ZIP<input value={form.zip} onChange={(event) => update({ zip: event.target.value })} className={fieldClass()} /></label><label className="text-sm text-slate-600">Preferred Contact<select value={form.preferredContact} onChange={(event) => update({ preferredContact: event.target.value })} className={fieldClass()}><option value="">Select</option><option>Phone</option><option>Email</option><option>Text</option></select></label></div></Section>
    <Section title="Interview"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm text-slate-600">{required("Interview Date/Time")}<input type="datetime-local" value={toLocalInput(form.scheduledAt)} onChange={(event) => update({ scheduledAt: event.target.value })} className={fieldClass(errors.scheduledAt)} />{errors.scheduledAt ? <span className="mt-1 block text-xs text-rose-600">{errors.scheduledAt}</span> : null}</label><label className="text-sm text-slate-600">Status<select value={form.status} onChange={(event) => update({ status: event.target.value as InterviewRecord["status"] })} className={fieldClass()}>{["Scheduled", "Completed", "Follow Up", "Offer", "Hired", "Declined", "No Show"].map((status) => <option key={status}>{status}</option>)}</select></label><label className="text-sm text-slate-600">Interview Outcome<select value={form.interviewOutcome} onChange={(event) => update({ interviewOutcome: event.target.value as InterviewRecord["interviewOutcome"] })} className={fieldClass()}><option value="">Select</option>{OUTCOMES.map((outcome) => <option key={outcome}>{outcome}</option>)}</select></label></div><p className="mt-4 text-sm font-medium text-slate-700">Recruiter Rating</p><div className="mt-2 flex flex-wrap gap-2">{RATINGS.map((rating) => <button key={rating} type="button" aria-pressed={form.rating === rating} onClick={() => update({ rating })} className={`min-w-11 ${controlClass(form.rating === rating)}`}>{rating}</button>)}</div></Section>
    <Section title="Employment Preferences"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm text-slate-600">Desired Pay<input value={form.desiredPay} onChange={(event) => update({ desiredPay: event.target.value })} className={fieldClass()} /></label><label className="text-sm text-slate-600">Employment Type<select value={form.employmentType} onChange={(event) => update({ employmentType: event.target.value })} className={fieldClass()}><option value="">Select</option><option>Full-time</option><option>Part-time</option><option>Either</option></select></label><label className="text-sm text-slate-600">Earliest Start Date<input type="date" value={form.earliestStartDate} onChange={(event) => update({ earliestStartDate: event.target.value })} className={fieldClass()} /></label><label className="text-sm text-slate-600">Travel Radius (minutes)<input type="number" min="0" value={form.travelRadiusMinutes ?? ""} onChange={(event) => update({ travelRadiusMinutes: event.target.value ? Number(event.target.value) : undefined })} className={fieldClass()} /></label><label className="text-sm text-slate-600 md:col-span-2">Case Recommendation<input value={form.caseRecommendation} onChange={(event) => update({ caseRecommendation: event.target.value })} placeholder="Name or placement guidance" className={fieldClass()} /></label><label className="text-sm text-slate-600 md:col-span-2">Link Existing Case (optional)<select value={form.caseRecommendationId ?? ""} onChange={(event) => update({ caseRecommendationId: event.target.value || undefined })} className={fieldClass()}><option value="">No linked case</option>{cases.map((caseItem) => <option key={caseItem.id} value={caseItem.id}>{caseItem.name} - {caseItem.city}, {caseItem.state}</option>)}</select></label></div></Section>
    <Section title="Availability"><p className="text-sm text-slate-600">Available Days</p><ToggleSet options={DAYS} values={form.availableDays} onChange={(availableDays) => update({ availableDays })} /><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-sm text-slate-600">Available Start Time<input type="time" value={form.preferredStartTime} onChange={(event) => update({ preferredStartTime: event.target.value })} className={fieldClass()} /></label><label className="text-sm text-slate-600">Available End Time<input type="time" value={form.preferredEndTime} onChange={(event) => update({ preferredEndTime: event.target.value })} className={fieldClass()} /></label></div></Section>
    <Section title="Experience"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm text-slate-600">Years in ABA<input type="number" min="0" value={form.yearsAba ?? ""} onChange={(event) => update({ yearsAba: event.target.value ? Number(event.target.value) : undefined })} className={fieldClass()} /></label><label className="text-sm text-slate-600">Years as RBT<input type="number" min="0" value={form.yearsRbt ?? ""} onChange={(event) => update({ yearsRbt: event.target.value ? Number(event.target.value) : undefined })} className={fieldClass()} /></label><label className="text-sm text-slate-600">Preferred Age Group<input value={form.preferredAgeGroup} onChange={(event) => update({ preferredAgeGroup: event.target.value })} className={fieldClass()} /></label><label className="text-sm text-slate-600">CentralReach Experience<select value={form.centralReachExperience} onChange={(event) => update({ centralReachExperience: event.target.value })} className={fieldClass()}><option value="">Select</option><option>Yes</option><option>No</option></select></label></div><div className="mt-3 flex flex-wrap gap-4 text-sm">{([ ["In-Home Experience", "inHomeExperience"], ["Clinic Experience", "clinicExperience"], ["Severe Behaviors Experience", "severeBehaviorsExperience"] ] as const).map(([label, key]) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={Boolean(form[key])} onChange={(event) => update({ [key]: event.target.checked })} />{label}</label>)}</div><label className="mt-3 block text-sm text-slate-600">Additional Experience Notes<textarea value={form.experience} onChange={(event) => update({ experience: event.target.value })} className={fieldClass()} rows={3} /></label></Section>
    <Section title="Certifications"><ToggleSet options={CERTIFICATIONS} values={form.certifications} onChange={(certifications) => update({ certifications })} />{form.certifications.includes("Other") ? <input value={form.certificationOther} onChange={(event) => update({ certificationOther: event.target.value })} placeholder="Other certification" className={fieldClass()} /> : null}</Section>
    <Section title="Skills"><ToggleSet options={SKILLS} values={form.skills} onChange={(skills) => update({ skills })} />{form.skills.includes("Other") ? <input value={form.skillOther} onChange={(event) => update({ skillOther: event.target.value })} placeholder="Other skill" className={fieldClass()} /> : null}</Section>
    <Section title="Quick Evaluation"><div className="grid gap-4 md:grid-cols-2">{EVALUATIONS.map(([label, key]) => <div key={key} className="min-w-0"><p className="text-sm font-medium text-slate-700">{label}</p><div className="mt-2 flex flex-wrap gap-2">{EVALUATION_GRADES.map((grade) => <button key={grade} type="button" aria-pressed={form[key] === grade} onClick={() => update({ [key]: grade })} className={controlClass(form[key] === grade)}>{grade}</button>)}</div></div>)}</div></Section>
    <Section title="Resume"><div className="flex flex-wrap items-center gap-3"><label className="cursor-pointer rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 focus-within:ring-2 focus-within:ring-blue-500 focus-within:ring-offset-2"><input type="file" accept=".pdf,.doc,.docx,.rtf,.txt,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => { const selectedFile = event.target.files?.[0] ?? null; if (!selectedFile) return; try { validateInterviewResumeFile(selectedFile); setFile(selectedFile); setResumeError(""); } catch (error) { setFile(null); setResumeError(error instanceof Error ? error.message : "Invalid resume file."); event.target.value = ""; } }} className="sr-only" />{form.resumeName || file ? "Replace Resume" : "Upload Resume"}</label>{file ? <span className="text-sm font-medium text-blue-700">Ready to upload: {file.name}</span> : null}{form.resumeName && !file ? <><span className="text-sm text-slate-700">Resume: {form.resumeName}</span><button type="button" onClick={() => onViewResume(form)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-800 hover:border-blue-500 hover:bg-blue-50">View</button><button type="button" onClick={() => onRemoveResume(form)} className="rounded-lg border border-rose-300 bg-white px-3 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50">Remove</button></> : null}</div>{resumeError ? <p className="mt-2 text-sm text-rose-700">{resumeError}</p> : null}<p className="mt-2 text-xs text-slate-500">PDF, DOC, DOCX, RTF, or TXT up to 10 MB. Save Interview uploads the selected file.</p></Section>
    <Section title="Background / Onboarding Checklist"><div className="grid gap-2 sm:grid-cols-2">{ONBOARDING.map(([label, key]) => <label key={key} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><input type="checkbox" checked={form[key]} onChange={(event) => update({ [key]: event.target.checked })} />{label}</label>)}</div></Section>
    <Section title="Recruiter Notes"><textarea value={form.recruiterNotes} onChange={(event) => update({ recruiterNotes: event.target.value })} className={fieldClass()} rows={4} /></Section>
  </div><div className="sticky bottom-0 flex justify-end gap-2 border-t border-slate-200 bg-white px-5 py-4"><button type="button" onClick={onClose} disabled={saving} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold">Cancel</button><button type="button" disabled={saving} onClick={() => { if (validate()) onSave(form, file); }} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save Interview"}</button></div></div></div>;
}