"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useMemo, useState } from "react";
import { DatabaseState } from "@/app/components/database-state";
import { getListNavigationParams, restoreListScroll } from "@/app/components/detail-navigation";
import { formatUsDate, formatUsDateTime } from "@/app/data/display-formatters";
import { type InterviewRecord, type InterviewStatus } from "@/app/data/interviews";
import { deleteInterviewResume, getInterviewResumeUrl, uploadInterviewResume } from "@/app/data/interviews-adapter";
import { InterviewFormModal } from "@/app/interviews/interview-form-modal";
import { useInterviews } from "@/app/data/interviews-store";
import { useTechnicianDatabase } from "@/app/data/technicians-store";
import { normalizeState } from "@/app/data/technicians-utils";
import { getSupabaseBrowserClient, getSupabaseConfigError } from "@/app/lib/supabase/client";

type Draft = Omit<InterviewRecord, "id"> & { id?: string };
function emptyInterview(): Draft { return { candidateName: "", phone: "", email: "", city: "", state: "NM", zip: "", scheduledAt: "", status: "Scheduled", experience: "", desiredPay: "", employmentType: "", availability: "", availableDays: [], preferredStartTime: "", preferredEndTime: "", travelRadiusMinutes: undefined, centralReachExperience: "", preferredContact: "", rating: "", recruiterNotes: "", yearsAba: undefined, yearsRbt: undefined, inHomeExperience: undefined, clinicExperience: undefined, severeBehaviorsExperience: undefined, preferredAgeGroup: "", earliestStartDate: "", certifications: [], certificationOther: "", skills: [], skillOther: "", communicationScore: undefined, professionalismScore: undefined, abaExperienceScore: undefined, scheduleFlexibilityScore: undefined, overallRecommendationScore: undefined, communicationGrade: undefined, professionalismGrade: undefined, abaExperienceGrade: undefined, scheduleFlexibilityGrade: undefined, overallRecommendationGrade: undefined, offerPay: "", offerNotes: "", offerDate: "", interviewOutcome: "", caseRecommendation: "", caseRecommendationId: undefined, resumePath: "", resumeName: "", resumeMimeType: "", backgroundCheckSubmitted: false, backgroundCleared: false, drugScreen: false, cprVerified: false, rbtLicenseVerified: false }; }
function toLocalInput(value: string) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function onboardingProgress(item: InterviewRecord) { return [item.backgroundCheckSubmitted, item.backgroundCleared, item.drugScreen, item.cprVerified, item.rbtLicenseVerified].filter(Boolean).length; }

function InterviewsPageContent() {
  const { interviews, loading, errorMessage, refreshInterviews, saveInterview, setInterviewStatus } = useInterviews();
  const { cases } = useTechnicianDatabase();
  const searchParams = useSearchParams();
  const [search, setSearch] = useState(""); const [stateFilter, setStateFilter] = useState("All"); const [statusFilter, setStatusFilter] = useState("All");
  const [form, setForm] = useState<Draft | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => {
    const editId = searchParams.get("edit");
    if (searchParams.get("add") === "1" && !form) {
      const timer = window.setTimeout(() => setForm(emptyInterview()), 0);
      return () => window.clearTimeout(timer);
    }
    const interview = interviews.find((item) => item.id === editId);
    if (!interview || form) return;
    const timer = window.setTimeout(() => setForm({ ...interview, scheduledAt: toLocalInput(interview.scheduledAt) }), 0);
    return () => window.clearTimeout(timer);
  }, [form, interviews, searchParams]);
  useEffect(() => {
    const params = getListNavigationParams();
    const timer = window.setTimeout(() => {
      setSearch(params.get("search") ?? "");
      setStateFilter(params.get("state") ?? "All");
      setStatusFilter(params.get("status") ?? "All");
      restoreListScroll(params);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  const visible = useMemo(() => interviews.filter((item) => (!search.trim() || item.candidateName.toLowerCase().includes(search.trim().toLowerCase())) && (stateFilter === "All" || normalizeState(item.state) === stateFilter) && (statusFilter === "All" || item.status === statusFilter)), [interviews, search, stateFilter, statusFilter]);
  const summary = useMemo(() => { const now = new Date(); const today = now.toISOString().slice(0, 10); const month = today.slice(0, 7); return { today: interviews.filter((item) => item.status === "Scheduled" && item.scheduledAt.slice(0, 10) === today).length, upcoming: interviews.filter((item) => item.status === "Scheduled" && item.scheduledAt >= now.toISOString()).length, followUp: interviews.filter((item) => item.status === "Follow Up").length, offers: interviews.filter((item) => item.status === "Offer").length, hired: interviews.filter((item) => item.status === "Hired" && item.scheduledAt.slice(0, 7) === month).length }; }, [interviews]);
  const save = async (draft: Draft, file: File | null) => { setSaving(true); let uploadedPath = ""; try { const firstSave = await saveInterview({ ...draft, scheduledAt: new Date(draft.scheduledAt).toISOString() }); if (!firstSave.ok) { setMessage(firstSave.message); return; } let saved = firstSave.interview; if (file) { const client = getSupabaseBrowserClient(); if (!client) { setMessage(getSupabaseConfigError() ?? "Supabase client is unavailable."); return; } const resume = await uploadInterviewResume(client, saved.id, file); uploadedPath = resume.path; const resumeSave = await saveInterview({ ...saved, resumePath: resume.path, resumeName: resume.name, resumeMimeType: resume.mimeType }); if (!resumeSave.ok) { await deleteInterviewResume(client, uploadedPath); uploadedPath = ""; setMessage(resumeSave.message); return; } if (draft.resumePath && draft.resumePath !== resume.path) await deleteInterviewResume(client, draft.resumePath); saved = resumeSave.interview; } setMessage(file ? `Saved ${saved.candidateName}. Resume uploaded.` : `Saved ${saved.candidateName}.`); setForm(null); } catch (error) { if (uploadedPath) { const client = getSupabaseBrowserClient(); if (client) await deleteInterviewResume(client, uploadedPath).catch(() => undefined); } setMessage(error instanceof Error ? error.message : "Unable to save the interview."); } finally { setSaving(false); } };
  const removeResume = async (draft: Draft) => { if (!draft.id || !draft.resumePath || !confirm(`Delete ${draft.resumeName}?`)) return; const client = getSupabaseBrowserClient(); if (!client) { setMessage(getSupabaseConfigError() ?? "Supabase client is unavailable."); return; } setSaving(true); try { await deleteInterviewResume(client, draft.resumePath); const result = await saveInterview({ ...draft, resumePath: "", resumeName: "", resumeMimeType: "" }); setMessage(result.ok ? "Resume deleted." : result.message); if (result.ok) setForm(null); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to delete the resume."); } finally { setSaving(false); } };
  const changeStatus = async (id: string, status: InterviewStatus) => { const result = await setInterviewStatus(id, status); setMessage(result.ok ? `Status changed to ${status}.` : result.message); };
  if (loading) return <DatabaseState title="Loading interviews" message="Fetching the recruiting pipeline from Supabase." />;
  if (errorMessage) return <DatabaseState title="Interviews unavailable" message={errorMessage} actionLabel="Retry" onAction={() => void refreshInterviews()} />;
  return <div className="min-h-screen bg-slate-50 p-4 text-slate-800 sm:p-6 lg:p-8"><main className="mx-auto max-w-[1500px]"><header className="mb-6 flex flex-col gap-4 rounded-[28px] bg-gradient-to-r from-blue-700 via-blue-600 to-cyan-500 p-6 text-white shadow-xl shadow-blue-100 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.24em] text-blue-100">Recruiting Pipeline</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">Interviews</h1><p className="mt-2 text-sm text-blue-50">Structured candidate evaluation and hiring workflow.</p></div><button type="button" onClick={() => { setForm(emptyInterview()); setMessage(""); }} className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-blue-700">Add Interview</button></header>
    <section className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Today", summary.today], ["Upcoming", summary.upcoming], ["Follow Ups", summary.followUp], ["Offers", summary.offers], ["Hired This Month", summary.hired]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p></div>)}</section>
    <section className="mb-5 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search candidate name" className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm" /><select value={stateFilter} onChange={(event) => setStateFilter(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="All">All states</option><option value="IA">Iowa</option><option value="NM">New Mexico</option></select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="All">All statuses</option>{["Scheduled", "Completed", "Follow Up", "Offer", "Hired", "Declined", "No Show"].map((status) => <option key={status}>{status}</option>)}</select></section>{message ? <p className="mb-4 rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</p> : null}
  <section className="space-y-3">{visible.map((interview) => <article key={interview.id} className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><h2 className="font-semibold text-slate-900">{interview.candidateName}</h2><p className="mt-1 text-sm text-slate-500">{interview.city}, {interview.state} | {formatUsDateTime(interview.scheduledAt)}</p><p className="mt-1 text-sm text-slate-600">{interview.desiredPay || "Pay TBD"} | {interview.employmentType || "Employment type TBD"} | Rating {interview.rating || "TBD"} | {interview.interviewOutcome || "Outcome TBD"}</p><p className="mt-1 text-xs text-slate-500">Start: {formatUsDate(interview.earliestStartDate) || "TBD"} | Onboarding: {onboardingProgress(interview)}/5{interview.caseRecommendation ? ` | Case: ${interview.caseRecommendation}` : ""}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{interview.status}</span>{interview.phone ? <a href={`tel:${interview.phone}`} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Call</a> : null}{interview.email ? <a href={`mailto:${interview.email}`} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Email</a> : null}{interview.status === "Scheduled" ? <button type="button" onClick={() => void changeStatus(interview.id, "Completed")} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Complete</button> : null}<button type="button" onClick={() => setForm({ ...interview, scheduledAt: toLocalInput(interview.scheduledAt) })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Edit</button><Link href={`/interviews/${interview.id}`} className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white">Open Profile</Link></div></article>)}{visible.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">No interview candidates match these filters.</div> : null}</section>
    {form ? <InterviewFormModal initial={form} cases={cases} saving={saving} onClose={() => setForm(null)} onSave={(draft, file) => void save(draft, file)} onRemoveResume={(draft) => void removeResume(draft)} onViewResume={(draft) => { const client = getSupabaseBrowserClient(); if (!client || !draft.resumePath) { setMessage(getSupabaseConfigError() ?? "No resume is available to view."); return; } void getInterviewResumeUrl(client, draft.resumePath).then((url) => window.open(url, "_blank", "noopener,noreferrer")).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Unable to open the resume.")); }} /> : null}
  </main></div>;
}

export default function InterviewsPage() {
  return <Suspense fallback={<DatabaseState title="Loading interviews" message="Preparing the recruiting pipeline." />}><InterviewsPageContent /></Suspense>;
}